### ISSUE TITLE
dependency resolving

### ISSUE THREAD

**Issue by e-belair** [dart-lang/reflectable#175] opened 2019-05-14 13:19 UTC
Hi, since a recent update of sdk to 2.3 I had to upgrade build_runner and build_web_compilers.
Now I can't figure out with this dependency version error:
```
/usr/lib/dart/bin/pub upgrade
Resolving dependencies...
Because reflectable >=2.0.10 depends on build_runner_core >=1.0.0 <3.0.0 and build_runner >=1.3.0 depends on build_runner_core ^3.0.0, reflectable >=2.0.10 is incompatible with build_runner >=1.3.0.
So, because agde_mobilite_web depends on both reflectable ^2.0.12 and build_runner ^1.3.0, version solving failed.
Process finished with exit code 1
```
pubspec.yml file:
```
environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha+19
  http: ^0.11.0
  stream_transform: ^0.0.6
  angular_components: ^0.10.1
  sass_builder: ^2.0.2
  bulma_sass: ^0.7.1+1
  intl: ^0.15.7
  cookie_jar: ^0.0.7
  dio:
  mdc_web:
  crypto:
  uuid: ^1.0.3
  reflectable: ^2.0.12
  recase:

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^1.3.0
  build_test: ^0.10.2
  build_web_compilers: ^2.0.0
  built_html: ^0.1.0
  test: ^1.0.0
  coverage: ^0.12.3
  mockito: ^3.0.0-beta+1
  pageloader: ^3.0.3
  json_serializable: ^2.0.1
  grinder:
  path:
```
How can I resolve this issue?

**Comment by eernstg** [comment] 2019-05-20 12:32
This issue is essentially the same as #173, which is concerned with porting reflectable to work with analyzer version 0.35 and up. That version eliminates a number of features that reflectable is using, and I haven't resolved how to restore the corresponding functionality.

The connection is as follows: The requirement `build_runner => 1.3.0` implies `build_runner_core ^3.0.0`, and already `build_runner_core >=2.0.2` implies `analyzer >=0.35.0 <0.37.0`.

So I'll close this issue as a duplicate of #173.

**Closed by eernstg** 2019-05-20 12:32 UTC

**Comment by e-belair** [comment] 2019-05-20 13:55
Well I'll subscribe to the #173 notifications
Thank you for your answer
