### ISSUE TITLE
Attempt to generate code for an unsupported kind of type: void (VoidTypeImpl). Generating `dynamic`.

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/reflectable#138] opened 2018-07-06 07:24 UTC
Could you please be a bit more specific on this warning? Why gets something generated for `void` at all?

I have no idea where to search for the the problem.
 
This is how the main looks like:

```dart
import 'package:console_log_handler/console_log_handler.dart';

import 'package:mdl/mdl.dart';
import 'package:mdl/mdldemo.dart';

import 'main.reflectable.dart';

main() async {
    configLogging();
    initializeReflectable();

    registerDemoAnimation();
    registerMdl();

    await componentFactory().run();
}
```
So the problem can't be in main - it must be somewhere in mdl.dart...

```bash
pub run build_runwebdev serve
[INFO] Setting up file watchers completed, took 33ms
[INFO] Waiting for all file watchers to be ready completed, took 426ms
[INFO] Building new asset graph completed, took 1.6s
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[WARNING] reflectable on web/main.dart:
Attempt to generate code for an unsupported kind of type: void (VoidTypeImpl). Generating `dynamic`.
[WARNING] reflectable on web/main.dart:
Attempt to generate code for an unsupported kind of type: void (VoidTypeImpl). Generating `dynamic`.
[INFO] Running build completed, took 32.1s
[INFO] Caching finalized dependency graph completed, took 156ms
[INFO] Succeeded after 32.3s with 314 outputs (2322 actions)
Serving `web` on http://localhost:8080
```

**Comment by eernstg** [comment] 2018-07-06 07:47
Indeed, that error message should be more informative.

The problem is real, though, because it happens when the code for the value returned by `reflectedType` or `dynamicReflectedType` is generated. There is no entity of type `Type` corresponding to the type `void`, and it is a syntax error (OK, a tool can make it a static semantic error and use a less strict parser, but it's certainly an error at compile-time) to evaluate `void` as an expression, so the code generator sticks `dynamic` in those locations in the "reflectable database" where it should have used `void` and emits the warning.

A similar situation arises when generating code which should yield the `Type` for a type that is or contains a type variable from an enclosing scope: We do not have the primitives required in order to produce the actual `Type` object for that (say, the type for `Iterable<E>` in the context of a list), so we generate code that will return the `Type` for `Iterable<dynamic>` and emit the warning.

Note that this situation easily arises because of quantification (when we generate mirrors for a lot of classes) when used together with anything that requires one of the reflected type getters.

I'll use this issue to keep track of the need to give more information about the source locations associated with the types that incur this kind of imprecision.

**Comment by eernstg** [comment] 2018-07-06 07:54
Depending on the size of your project, you could inspect list literals of type `List<Type>` in the generated code and search for `dynamic`. If any of those "should have been" `void` you've found the spot where such a warning was generated.

**Comment by eernstg** [comment] 2018-07-06 14:41
Marking this as a bug because the emitted information must be improved. The underlying problem (missing primitives) will not be eliminated, so even after this issue is closed there will be some missing elements in the support for the `reflected..Type` methods.

**Comment by eernstg** [comment] 2018-08-17 13:48
> Could you please be a bit more specific on this warning?

Release 2.0.3 of reflectable emits a precise source code location (line number, column) for each of these situations. I believe that this addresses the original concern of this issue: Closing.

**Closed by eernstg** 2018-08-17 13:48 UTC
Labels: bug
