### ISSUE TITLE
[SEVERE] when building flutter main();

### ISSUE THREAD

**Issue by matejthetree** [dart-lang/reflectable#118] opened 2018-03-21 23:43 UTC
I do basic example, expect that I do flutter app.

I get this warning on build

```
[SEVERE] TransformerBuilder[Reflectable] on reflection_test|lib/main.dart: Unable to resolve asset ID for "dart:ui"
```

**Comment by zoechi** [comment] 2018-03-22 08:32
Please provide more information.
How did you create the project?
What changes did you make (added dependencies)?
What is the output of `flutter doctor -v`?

**Comment by eernstg** [comment] 2018-03-22 11:03
This could well be because 'dart:ui' is a 'system library' that reflectable does not know. I've just tentatively added "dart:ui" to the set of names of known system libraries in code that will be reflectable 2.0.0-dev.3.0. This may create the danger that generated code can contain `import 'dart:ui';` even outside Flutter, and it will then not compile, but that should only happen when the program already won't compile outside Flutter (so "that program is broken in this context, anyway").

**Comment by eernstg** [comment] 2018-03-22 14:38
In https://github.com/dart-lang/reflectable/issues/117 I asked for a setup that demonstrated the problem; it would be great if such a setup could also demonstrate this problem at the same time (maybe that comes for free?).

**Comment by eernstg** [comment] 2018-08-17 13:15
The issue reported [initially](https://github.com/dart-lang/reflectable/issues/118#issue-307456353) still exists, but this reflectable &amp; Flutter [example repo](https://github.com/eernstg/reflectable-flutter) allows for generating code using reflectable and running the example both from the command line and from Android Studio.

**Comment by eernstg** [comment] 2018-08-21 14:59
Here's another situation where the same symptom arises: https://github.com/dart-lang/build/issues/733.

**Comment by s-bauer** [comment] 2018-08-22 08:10
Besides the dart:ui issue there is another problem occurring with version 0.6.0. Given the example repository https://github.com/eernstg/reflectable-flutter using the described steps to generate the reflectable it fails with the following Exception:

```
[SEVERE] reflectable on lib/main.dart:

NoSuchMethodError: The getter 'id' was called on null.
Receiver: null
Tried calling: id
```

Tracked in https://github.com/dart-lang/reflectable/issues/145

**Comment by eernstg** [comment] 2018-08-22 13:17
Fixed a null bug, published 2.0.4, and closed #145.

(But the SEVERE 'dart:ui' message that this issue deals with still exists, so this one remains open).

**Comment by EthimjosVelo** [comment] 2018-08-22 16:12
Updating to 2.0.4 fixed this problem for me. If the bug persist, try to upgrade Flutter and see if it fixes the problem.

**Comment by eernstg** [comment] 2018-10-26 13:19
Closing: I cannot reproduce the issue reported here any more. Please create a new issue if it still occurs for you.

**Closed by eernstg** 2018-10-26 13:19 UTC
Labels: bug
