### ISSUE TITLE
Facing error: `NoSuchMethodError: The method 'classMirrorForInstance' was called on null`

### ISSUE THREAD

**Issue by moznion** [dart-lang/reflectable#131] opened 2018-06-05 06:46 UTC
Dart version: `Dart VM version: 2.0.0-dev.59.0 (Tue May 29 22:11:36 2018 +0200) on "macos_x64"`
Reflectable version: `^2.0.1`

A repository to reproduce is here: https://github.com/moznion/dart_reflection_error_example
When `reflector` and `reflectee` are separated from `main`, occurs the error.

However following concatenated code works rightly:

```dart
import 'package:reflectable/reflectable.dart';
import './main.reflectable.dart';

class MyReflectable extends Reflectable {
  const MyReflectable() : super(invokingCapability, declarationsCapability);
}

const myReflectable = const MyReflectable();

@MyReflectable()
class Foo {
  int bar = 42;
  int buz() {
      return 42;
  }
}

main() {
  initializeReflectable();

  Foo instance = new Foo();
  InstanceMirror instanceMirror = myReflectable.reflect(instance);
  ClassMirror classMirror = instanceMirror.type;
}
```

Are there any solutions?

**Comment by eernstg** [comment] 2018-06-05 15:59
Try these adjustments: [adjustments.txt](https://github.com/dart-lang/reflectable/files/2073069/adjustments.txt). I couldn't immediately reproduce the issue. But I also can't see that you've generated any code, so I added a comment to `main.dart` about how to do that. With that, it runs here.

**Comment by eernstg** [comment] 2018-06-05 16:02
The link to 'adjustments.txt' seems to take forever to follow, so here's the text of that file as well:

```
diff --git a/lib/main.dart b/example/main.dart
similarity index 51%
rename from lib/main.dart
rename to example/main.dart
index 44df24a..df19764 100644
--- a/lib/main.dart
+++ b/example/main.dart
@@ -1,7 +1,9 @@
 import 'package:reflectable/reflectable.dart';
-import './main.reflectable.dart';
-import './foo.dart';
-import './my_reflectable.dart';
+import 'package:dart_reflection_example/foo.dart';
+import 'package:dart_reflection_example/my_reflectable.dart';
+import 'main.reflectable.dart';
+
+// Use `pub run build_runner build example` to initiate code generation.
 
 main() {
   initializeReflectable();
diff --git a/pubspec.yaml b/pubspec.yaml
index 4a4e005..4974cf4 100644
--- a/pubspec.yaml
+++ b/pubspec.yaml
@@ -1,10 +1,11 @@
-name: example
+name: dart_reflection_example
 description: A sample command-line application.
 
 environment:
   sdk: '>=2.0.0-dev.52.0 <2.0.0'
 
 dependencies:
+  build_runner: any
   reflectable: ^2.0.1
 
 dev_dependencies:
```

**Comment by moznion** [comment] 2018-06-06 06:28
Thank you for your response.
I applied the above patch and moved `main.dart` to under the `example` directory, then it works fine.

Is this point "user of the `reflectable` must import packages of reflectable and reflectee with `package:` prefix"?

**Comment by eernstg** [comment] 2018-06-11 08:45
> Is this point "user of the reflectable must import packages of reflectable
> and reflectee with `package:` prefix"?

No, I believe that the `build` package and the `pub run build_runner ...` commands assume that there will not be any entry points (i.e., Dart files containing `main` which will be the root of a program for execution) in `lib`, and it is also a common recommendation to never put any entry points there (the following is from [Pub Package Layout Conventions](https://www.dartlang.org/tools/pub/package-layout)):

> Note that only libraries should be in lib. Entrypoints—Dart scripts with a 
> main() function—cannot go in lib. 

So the problem was that no code generation would ever take place as long as you'd keep `main.dart` in `lib`. In case you encounter some other situation where no code generation takes place you should be able to see it in the response from the run of `pub run build_runner ...`:

```
$ pub run build_runner build lib
[INFO] Generating build script completed, took 387ms
[INFO] Building new asset graph completed, took 443ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Running build completed, took 4ms
[INFO] Caching finalized dependency graph completed, took 33ms
[INFO] Succeeded after 45ms with 0 outputs (0 actions)
```
The giveaway is `0 outputs`, especially if this is the first run, or if you have just deleted all the `*.reflectable.dart` files in all subdirectories.

PS: Thanks! 🏖

**Comment by eernstg** [comment] 2018-06-11 08:46
Closing: I believe this issue is now resolved. Please open a new one if there are any remaining issues.

**Closed by eernstg** 2018-06-11 08:46 UTC
