### ISSUE TITLE
Instance ClassMirror#superclass throws in 5.2

### ISSUE THREAD

**Issue by lassedamgaard** [dart-lang/reflectable#77] opened 2016-03-01 15:15 UTC
In 0.4.0 the below program prints the name of `Bar` superclass `Foo`. In 0.5.2 it throws:
```
Exception: Requesting mirror on un-marked class, superclass of 'Bar'
  ClassMirrorBase.get:superclass	
  main	
  main
```

``` dart
import 'package:reflectable/reflectable.dart';

class ReflectableClass extends Reflectable {
  const ReflectableClass()
      : super(declarationsCapability, superclassQuantifyCapability);
}

@ReflectableClass()
class Foo {}

@ReflectableClass()
class Bar extends Foo {}

main() {
  print(const ReflectableClass().reflect(new Bar()).type.superclass.simpleName);
}
```

**Comment by eernstg** [comment] 2016-03-01 16:48
The problem is primarily that the error message is misleading. It is correct that the specified operation cannot be carried out, because there is no `TypeRelationsCapability`. But when it encounters the magic "there is no such thing" value in its `superclass` field it does not take it into account that it could be both because that class is unmarked and because there is no type relations capability.

So in your code it should be enough to add `typeRelationsCapability` to your reflector, and then you don't have to wait for the improved error message.

**Comment by lassedamgaard** [comment] 2016-03-01 18:34
Thank, you're right `typeRelationsCapability` fixed it. I thought I had gone over the capability docs... https://github.com/dart-lang/reflectable/issues/70 would have helped here.

**Comment by eernstg** [comment] 2016-03-02 08:47
Indeed, and it is coming!

**Comment by eernstg** [comment] 2016-03-31 15:13
Fixed by https://github.com/dart-lang/reflectable/commit/82fe5d7ce9b388e57a9746a9c4c74393f9e15c05.

**Closed by eernstg** 2016-03-31 15:13 UTC
Labels: bug
