### ISSUE TITLE
Help with setting up reflection in Flutter

### ISSUE THREAD

**Issue by matejthetree** [dart-lang/reflectable#117] opened 2018-03-21 23:41 UTC
Hello,

I was able to set up the basic example with the code running inside main().

But now I want to create new class to play with reflection there a little bit more, and I get this error

```
E/flutter ( 6705): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 6705): 'package:reflectable/src/reflectable_transformer_based.dart': Failed assertion: line 197 pos 14: '_dataCache != null': is not true.
```

Here is my code

```
class Reflector extends Reflectable {
  const Reflector()
      : super(invokingCapability); // Request the capability to invoke methods.
}

const reflector = const Reflector();

void main() {

  initializeReflectable();

  var reflectTest = new ReflectTest()
  ..invokingCapabilityTest();

  runApp(new MyApp());


}
```

and `reflect_test.dart`
```
import 'package:reflectable/mirrors.dart';
import 'package:reflection_test/main.dart';

class ReflectTest {

  void invokingCapabilityTest(){
    A x = new A(10);
    // Reflect upon [x] using the const instance of the reflector:
    InstanceMirror instanceMirror = reflector.reflect(x);
    int weekday = new DateTime.now().weekday;
    // On Fridays we test if 3 is greater than 10, on other days if it is less
    // than or equal.
    String methodName = weekday == DateTime.FRIDAY ? "greater" : "lessEqual";
    // Reflectable invocation:
    print(instanceMirror.invoke(methodName, [3]));

  }
}

@reflector // This annotation enables reflection on A.
class A {
  final int a;
  A(this.a);
  greater(int x) => x > a;
  lessEqual(int x) => x <= a;
}
```

Now, why do I get error? If I try to add `reflection_test.dart` to build script I get 
```
[INFO] TransformerBuilder[Reflectable] on reflection_test|lib/reflect_test.dart: Entry point: reflection_test|lib/reflect_test.dart has no member called `main`.
```

**Comment by zoechi** [comment] 2018-03-22 08:33
How did you add reflectable dependency in `pubspec.yaml`?

**Comment by eernstg** [comment] 2018-03-22 12:22
Using reflectable in the context of Flutter is new. The null valued `_dataCache` is clearly a bug, but I cannot immediately reproduce it. The following works fine on the plain vm (which sort of helps isolating remaining problems to the Flutterness of your setup ;-):

```dart
// FILE scratch_test.dart

import 'package:reflectable/reflectable.dart';
import 'scratch_test_lib.dart';
import 'scratch_test.reflectable.dart';

class Reflector extends Reflectable {
  const Reflector()
      : super(invokingCapability); // Request the capability to invoke methods.
}

const reflector = const Reflector();

void main() {
  initializeReflectable();
  var reflectTest = new ReflectTest()..invokingCapabilityTest();
  print(reflectTest);
  // runApp(new MyApp());
}
```

```dart
// FILE: scratch_test_lib.dart

import 'package:reflectable/mirrors.dart';
import 'scratch_test.dart';

class ReflectTest {

  void invokingCapabilityTest(){
    A x = new A(10);
    // Reflect upon [x] using the const instance of the reflector:
    InstanceMirror instanceMirror = reflector.reflect(x);
    int weekday = new DateTime.now().weekday;
    // On Fridays we test if 3 is greater than 10, on other days if it is less
    // than or equal.
    String methodName = weekday == DateTime.friday ? "greater" : "lessEqual";
    // Reflectable invocation:
    print(instanceMirror.invoke(methodName, [3]));

  }
}

@reflector // This annotation enables reflection on A.
class A {
  final int a;
  A(this.a);
  greater(int x) => x > a;
  lessEqual(int x) => x <= a;
}
```

**Comment by matejthetree** [comment] 2018-03-22 23:50
I imported it with path ../reflectable as I downloaded code from github repo.

Here is repo: https://github.com/matejthetree/reflectable_bugs

I am using android emulator to test this.

Go commit by commit from the beginning. Commit messages contain the bug that I got.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.1.5, on Mac OS X 10.13.3 17D102, locale en-HR)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
[✓] Connected devices (2 available)
```

Tell me if you need more data

**Comment by eernstg** [comment] 2018-03-26 16:40
I didn't get around to look at this today, and I'm on vacation for the rest of this week, but I'll return to the matter on Tuesday April 3rd.

**Comment by xrd** [comment] 2018-05-08 22:25
👍 

I'd really love to see an example of using reflectable with flutter. I'm having trouble getting it working and would love a good starting point like this example repository.

**Comment by matejthetree** [comment] 2018-05-09 00:59
Can you post your code to see what is going wrong. In the end I used reflectable with pure dart, but it should all be the same.

**Comment by eernstg** [comment] 2018-05-09 11:29
I'll definitely need to get the speed of my calendar calibrated, there's no way my previous comment here can be 44 days old. ;-)

**Comment by xrd** [comment] 2018-05-11 21:34
I suppose the big question is this: all the examples I see from reflective ask you to annotate a class a priori, and then import the generated files inside the same source file in which you add the annotation to the class. I'd like to do something that does not require this. I would love to have a library that someone can include in their project, and that library provides an annotation that can provide a method which ingests a class, and then inside the library do the reflection to dynamically determine methods and call them. Is this possible?

**Comment by eernstg** [comment] 2018-05-13 21:44
With reflectable, you don't have to annotate a class a priori in order to get reflection support for it. You can see an example in [this test](https://github.com/dart-lang/test_reflectable/blob/master/test/global_quantify_test.dart) where the class `Mark` is associated with the reflection support specified using `reflector`, and we could have used any class we want in place of `Mark`. So the target class does not need to depend on (that is, import, directly or indirectly) the library reflectable or anything associated with the reflectable package, it just needs to have a metadata of type `Mark`. This mechanism is associated with the class `GlobalQuantifyMetaCapability`.

If that's inconvenient (because the target class is in code that you can't edit, and it has no metadata at all) then you can also create the association based on the name of the class; check out the use of `GlobalQuantifyCapability` [the same test](https://github.com/dart-lang/test_reflectable/blob/master/test/global_quantify_test.dart).

Finally, you could take a look at a [slightly more complex test](https://github.com/dart-lang/test_reflectable/blob/master/test/meta_reflectors_test.dart) in order to see how it is possible to decouple many different aspects of the target classes and the software that provides reflection support for them.

For the scenario that you describe at the end, you'd need run-time reflection, not code generation&mdash;or you'd need to generate "support for absolutely everything", in which case you would be able to perform reflective operations on an instance of an arbitrary class (in the given program).

You could specify `@GlobalQuantifyCapability(r".*", reflector)` and then give `reflector` all the features that you want. However, that would violate the original motivation for having reflectable at all, namely that an unlimited run-time reflection feature turned out to make programs unacceptably large (esp. on the web).

**Comment by xrd** [comment] 2018-05-14 17:55
@eernstg Thanks for the very thorough explanation. I'll review these test examples. It clarifies a lot.

I've been somewhat abstract in what I want to do, and adding detail perhaps will help. I want to write a library to bring up a flutter app with the initial state (probably YAML) when running under test. Having the widget state explicitly written out **declaratively** as YAML means an app author can define many situations in which the app can run, but not have to program the path there imperatively by clicking buttons, etc.  

So, I get the concerns about reflectable having a goal of being small under all platforms inclusive of the web. But, this library would only need to change execution of a flutter app and only when running under test and only when the test execution was "special" (like with an environment variable). So, does reflectable provide an option to do this, or should I consider something else given the design goals of reflectable? 

I'll keep digging, but if you think I am wasting my time, I'd appreciate the guidance.

**Comment by eernstg** [comment] 2018-05-14 21:19
> flutter app with the initial state (probably defined as YAML)

I don't know whether that would work (well) with Flutter, so you'd need to bring up questions related to that (or trying to do that) as a flutter issue. But it does sound like it might go against the normal way to write Flutter apps so it would make sense to double check that it's a viable plan.

The reflectable library is actually just a regular Dart library that knows how to interpret a certain kind of data. That data is created by `pub run build_runner <some-directory>` based on static analysis of the source code of each entry point (each "main file"), and it's basically just a database of Dart functions and other values that are capable of working as mirrors for all the kinds of language entities that you have requested reflection support for. So reflectable-the-library just runs regular Dart code, it doesn't change the execution of a Flutter app, and you could have written all that generated code yourself (but you'd get bored ;-).

So the question is basically whether you can request and get reflection support for a special type of execution ('only when running under test and only when the test execution was "special" (like with an environment variable)'), and that sounds like you'd just need to change the app: It should run `initReflectable()` in `main`, you should generate the code and the entry point (or some other library) should import the generated code, etc, and then you can use reflection as specified. You may be able to use two entry points (one includes reflection, the other doesn't), but otherwise there's no way (which is obvious to me, at least) to have reflection support when passing a certain option to the program execution, and not having it otherwise.

**Comment by eernstg** [comment] 2018-07-04 14:08
Closing: I think the following should be helpful here: https://github.com/eernstg/reflectable-flutter, https://github.com/flutter/flutter/issues/19049, https://stackoverflow.com/questions/51169706/flutter-reflection-with-reflectable-working-example-needed/51174186#51174186.

**Closed by eernstg** 2018-07-04 14:08 UTC

**Comment by eernstg** [comment] 2018-07-05 07:32
I closed it because I think we have a [working approach](https://github.com/eernstg/reflectable-flutter) to use reflectable in Flutter, which is the title of this issue. But, @xrd, if your concerns have not been addressed then please create a new issue.
