### ISSUE TITLE
Please update dependencies

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/reflectable#136] opened 2018-07-02 14:47 UTC
Hi, could you please update your build_runner dependencies?
8.3 always crashes on my Mac.
Thanks

**Comment by eernstg** [comment] 2018-07-02 15:24
Simple updates do not suffice. Looking into it.

**Comment by MikeMitterer** [comment] 2018-07-02 15:29
I cloned your lib changed those deps:

```
  build_config: ^0.3.0
  build_runner: ^0.9.0
  dart_style: 1.1.1
```
At least all the test in dryice with upgraded dependencies are on green...

**Comment by MikeMitterer** [comment] 2018-07-02 15:57
Booooom - now I know what you mean with "bug"... `pub run build_runner build` crashed. My dryice-tests must have used a cached version or so

**Comment by eernstg** [comment] 2018-07-02 16:46
Running with SDK (and tools) version 2.0.0-dev.60.0 works here, and so do 61 &ndash; 63, but from 64 and up it fails. Would you be able to use one of those older versions for now?

**Comment by eernstg** [comment] 2018-07-02 16:59
I don't get any error messages referring to files in `reflectable`, so I don't see exactly the same things that you see. I'll go home now, and take another look tomorrow.

**Comment by MikeMitterer** [comment] 2018-07-03 07:05
I switched to 2.xxx.63 - it works. Thanks so far

**Comment by MikeMitterer** [comment] 2018-07-03 08:10
I thought it works... I had to change the dependencies in you cloned packages to `build_runner: ^0.8.10` otherwise I ran into https://github.com/dart-lang/pub/issues/1932 with
```bash
NoSuchMethodError: Class '_SingleBuild' has no instance method 'runPostProcessBuilder'.
Receiver: Instance of '_SingleBuild'
Tried calling: runPostProcessBuilder(Instance of 'ModuleCleanup', Instance of 'AssetId', Instance of 'SingleStepReader', Instance of 'AssetWriterSpy', Instance of 'BuildForInputLogger', Instance of 'AssetGraph', Instance of 'PostProcessAnchorNode', 467)
``` 
Oh - and before I had to `pub global activate build_runner` to switch build_runner back to 0.8.10
x hours of try and error which Dart version works with wich constraints

**Comment by eernstg** [comment] 2018-07-11 14:36
I'm currently working on an update of reflectable to eliminate barback (which is deprecated at this point). That should take care of the version conflicts, but many things need to be changed in order to do that so it may not be in a working state right now (and I'm OOO during much of the rest of July&mdash;conference then vacation).

**Comment by MikeMitterer** [comment] 2018-07-19 06:40
Thanks! The earlier you have something to test for us the better. My problem is that I can't upgrade to higher versions of Dart at the moment (and some of the build-packages). I have to stick at dev.63...

**Comment by jakemac53** [comment] 2018-08-08 17:04
@eernstg are you still working on a version that removes the barback/build_barback dependencies?

**Comment by eernstg** [comment] 2018-08-08 17:10
Yes I am, except that all the time since I came back from vacation has been consumed by other things (e.g., lots of stuff on the language specification side of releasing Dart 2). I hope to make progress on reflectable tomorrow.

**Comment by eernstg** [comment] 2018-08-10 17:40
Some progress today, see [here](https://github.com/dart-lang/reflectable/issue_comments#issuecomment-412153959) for a few words about it.

**Comment by haarts** [comment] 2018-08-13 09:48
Using that branch I am able to use Pointy Castle again! Can't wait for it to land. ;)

**Comment by yoxel** [comment] 2018-08-15 17:46
Will there be a new version in pub soon? Thanks

**Comment by eernstg** [comment] 2018-08-15 17:55
Yes, just awaiting reviews.

**Comment by yoxel** [comment] 2018-08-15 18:58
Thank you. We're also stuck with Pointy Castle after upgrading to Aqueduct 3.0 / Dart 2

**Comment by eernstg** [comment] 2018-08-17 09:12
Closing: [2.0.3](https://pub.dartlang.org/packages/reflectable) is now available on pub.dartlang.org, working with stable release Dart 2 tools! For a Flutter example, please check [this repo](https://github.com/eernstg/reflectable-flutter) which was also updated accordingly.

**Closed by eernstg** 2018-08-17 09:12 UTC
Labels: bug

**Comment by valotas** [comment] 2018-09-01 19:34
@eernstg I have the same issue on [travis](https://travis-ci.org/valotas/mustache4dart/builds/423443745). Couldn't reproduce it locally though.

**Comment by valotas** [comment] 2018-09-01 19:46
Created #149 with my findings. It looks like the newest version of analyzer finds some problems.
