### ISSUE TITLE
Migrate off of code_transformers

### ISSUE THREAD

**Issue by natebosch** [dart-lang/reflectable#130] opened 2018-06-04 22:43 UTC
We should stop using `barback`, `build_barback`, and `code_transformers` dependencies and migrate to fully `package:build` based workflows including `buildStep.resolver`.

**Comment by eernstg** [comment] 2018-06-05 14:49
Indeed we should do that! @natebosch, do you know about any documents that would be helpful in order to get started?

**Comment by natebosch** [comment] 2018-06-05 19:52
I'm not sure how much needs to be migrated. https://github.com/dart-lang/build/blob/master/docs/from_barback_transformer.md is the general document for moving from the `Transformer` interface to the `Builder` interface but it doesn't have a lot of detail. For the most part the APIs are relatively similar and it's the restrictions that end up being the pain points.

**Comment by eernstg** [comment] 2018-06-11 09:10
@natebosch, thanks a lot!

**Comment by eernstg** [comment] 2018-08-10 17:39
Doesn't quite work yet, but here is a preview: https://github.com/dart-lang/reflectable/tree/eliminate_barback_jul18.

The generated code may contain ill-formed import statements of the form `import 'asset:...';`, and it seems to work if they are adjusted to `import 'package:..';` in a way which is typically obvious. Other than that, most things seem to work.

**Comment by eernstg** [comment] 2018-08-15 16:18
At this point the [eliminate_barback_jul18 branch](https://github.com/dart-lang/reflectable/tree/eliminate_barback_jul18) is running all tests successfully, and a review has been requested. Hopefully we can land it soon and make it release 2.0.3.

One issue remains (see [here](https://github.com/dart-lang/sdk/issues/34148)), which may cause some metadata to be ignored (in particular, [this one](https://github.com/dart-lang/test_reflectable/blob/5e9a29c8ee82d96f2be04f228c9b4099c10f50d8/test/meta_reflectors_meta.dart#L14) has no effect). A promising workaround is available (but the exact cause of the problem is not yet known, so there's some guesswork involved): Put another copy of that metadata on an import of `package:reflectable/reflectable.dart` in some other library that imports this library (such that we don't rely on using `AllReflectorsMetaReflector` or a similar class on an import before the analyzer has seen the declaration of that class itself). In the example, it could go [here](https://github.com/dart-lang/test_reflectable/blob/5e9a29c8ee82d96f2be04f228c9b4099c10f50d8/test/meta_reflectors_test.dart#L16).

**Comment by eernstg** [comment] 2018-08-17 09:10
Closing: [2.0.3](https://pub.dartlang.org/packages/reflectable) is now available on pub.dartlang.org, working with stable release Dart 2 tools! For a Flutter example, please check [here](https://github.com/eernstg/reflectable-flutter) which was also updated accordingly.

**Closed by eernstg** 2018-08-17 09:10 UTC
