### ISSUE TITLE
Code generation error when transforming protobuf generated classes

### ISSUE THREAD

**Issue by wienczny** [dart-lang/reflectable#43] opened 2015-10-13 11:39 UTC
When trying to transform the classes generated using protobuf an error message is issued for every message:

    'prefix5' has no member named 'reflectable_generated_main_library#_ReadonlyEnvelope'.
 
This message is repeated for every `_Readonly*` class generated. 
(see https://github.com/dart-lang/dart-protoc-plugin/issues/51 for an initial description)

**Comment by eernstg** [comment] 2015-10-13 12:20
Thanks! Do you have code which will reproduce the problem? (I couldn't see any references to code at https://github.com/dart-lang/dart-protoc-plugin/issues/51, and I'm not sure `git clone https://github.com/dart-lang/dart-protoc-plugin` will do).

**Comment by eernstg** [comment] 2015-10-13 13:21
Tried

```
...$ git clone 'https://github.com/dart-lang/dart-protoc-plugin'
...$ cd dart-protoc-plugin
...$ pub get
...$ pub build --mode=debug test
```

where the latter produces 14919 lines of diagnostic messages, but it ends in 'Build failed.', none of the messages mention `_Readonly`, and the 'build' directory tree is empty, so that wasn't enough.

Could you give some more input on how you can reproduce the problem?

**Comment by wienczny** [comment] 2015-10-13 14:05
It took some time to prepare a minimal example: https://github.com/wienczny/ReflectableBugExample
dart-protoc-plugin used is https://github.com/dart-lang/dart-protoc-plugin/commit/58a031cb2155f7aefb579860891f1188920541e7
The bug can be triggered inside the `ReflectableBugExample` by running `pub build`

**Comment by eernstg** [comment] 2015-10-13 14:10
Got it, thanks a lot!

**Comment by eernstg** [comment] 2015-10-13 14:15
Ah, sorry -- this is a very simple issue: The problem is that there is an attempt to access a private declaration in 'messages.pb.dart' and reflectable does not support access to private declarations.

**Comment by eernstg** [comment] 2015-10-13 14:21
Duplicate of #33.

**Comment by wienczny** [comment] 2015-10-13 14:28
If you mean manually modifying all `_Readonly*` in the generated code - I could do that. 
I just prefer a solution that worked across rebuilds, though.

**Comment by eernstg** [comment] 2015-10-13 14:29
And you don't have enough control over that code generation process to avoid the generation of that as a private name in the first place?

**Comment by sigurdm** [comment] 2015-10-14 09:46
We can sort private classes away when generating the code, I guess that is better than generating invalid code - not all classes might be in the users control to make public.

When sorting away a private member it could be logged with logger.fine so a pub build --verbose would reveal that it happened.

**Comment by eernstg** [comment] 2015-10-14 14:02
Reclassified as a bug: I forgot that we are actually generating that private name, which shouldn't happen in any case.

**Comment by eernstg** [comment] 2015-10-15 14:18
We're now avoiding to create the expressions that will not compile because they attempt to access a private declaration in a different library (commit 2d9b6f5584b921183faec6d2d5b8d09265175bd0 on reflectable). 

Looking at your explanation again, it looks like the private class was not annotated directly by you, it may instead have been selected by subtype quantification in a reflector that you hadn't even written, and the class itself might even have been generated. That would of course make it quite difficult to avoid that it gets included. But the above-mentioned update should help you.

**Closed by eernstg** 2015-10-15 14:18 UTC
Labels: bug
