### ISSUE TITLE
 Reflecting on un-marked type 'List' when I try to invokeGetter("last") on a List

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/reflectable#93] opened 2017-04-29 17:00 UTC
Below is what I tried so far - do you have a hint for me?
Thanks

```dart
import 'dart:html' as dom;

@GlobalQuantifyCapability(r"^dart.core.List", rtest)
@GlobalQuantifyCapability(r"^dart.core.Iterable", rtest)
@GlobalQuantifyCapability(r"^dart.core.Iterator", rtest)
import 'package:reflectable/reflectable.dart';
import 'package:reflectable/capability.dart';

class ReflectionTestAnnotation extends Reflectable {
    const ReflectionTestAnnotation() : super(

        invokingCapability,
        reflectedTypeCapability,
        typeCapability,
    );
}

const ReflectionTestAnnotation rtest = const ReflectionTestAnnotation();

@rtest
class Version {
    final int major;
    final int minor;

    Version(this.major, this.minor);
}

@rtest
class DartLang {
    final String name;
    final Version version;
    final String message;

    final List<String> names = [ "Mike", "Sarah", "Gerda"];

    DartLang(this.name, this.version, this.message);
}

void main() {
    final DartLang language = new DartLang("Dart1",new Version(1,23),"Your Dart app is running.");

    final InstanceMirror instanceMirror = rtest.reflect(language);
    final Object list = instanceMirror.invokeGetter("names");
    
    // Works - clear!
    print((instanceMirror.invokeGetter("names") as List).last);

    // Crashes
    print(rtest.reflect(list).invokeGetter("last"));

    final Object version = instanceMirror.invokeGetter("version");
    print(version.runtimeType);
    
    final Object major = rtest.reflect(version).invokeGetter("major");

      dom.querySelector('#output').text = major.toString();
}
```

**Comment by eernstg** [comment] 2017-05-01 16:11
Hi Mike! I believe `rtest.reflect(list)` fails because `list` is actually not an instance of `List`. Consider the following example, based on 'dart:mirrors':
```dart
import 'dart:mirrors';

final List<String> names = [ "Mike", "Sarah", "Gerda"];

main() {
  InstanceMirror namesMirror = reflect(names);
  print(namesMirror.type); // 'InstanceMirror on _GrowableList'.
  print(names.runtimeType); // 'List'.
  print(names.runtimeType == List); // 'false'.
}
```
So you may actually have a `_GrowableList` instance, and when the reflectable database is searched ("Do we have a mirror for this? Well, we need a mirror for a _GrowableList ..") it's only satisfied if it is able to find an exact match. There is no exact match because even though you asked for a mirror for `List`, there is no mirror for `_GrowableList`. Unfortunately, you can't even get the `_GrowableList` mirror anyway, because that's a private name that you can't look up outside the core library where `_GrowableList` is defined (so there is no way the reflectable transformer could generate regular Dart code that would have access to this type, and hence you can't just change the `GlobalQuantifyCapability` metadata to include it).

In this particular case there is an extra issue, because the `runtimeType` of that `_GrowableList` prints as `List`. This may be considered to "look better", but in this particular case it's of course more confusing than helpful.

We considered allowing mirrors and instances to have mismatches of this kind; that is, you would be able to have an instance of `_GrowableList` and it would be mirrored by a `List` mirror (or a mirror for some other supertype of `_GrowableList`). You might, for instance, always search up through supertypes when creating a mirror for any given object, and then just give it a mirror for that supertype.

However, this is a dangerous idea. For instance, the mirror would then happily report that your `_GrowableList` is a direct instance of `List` (e.g., `myMirror.type.reflectedType == List` would be true), it would "forget" things like covariantly specialized return types (say, if `_GrowableList` had a `int foo()` method and `List` had a `num foo()` then it would report that `foo` has return type `num`, even though it is actually `int`); it would also forget non-inherited members (say, if `_GrowableList` declares a variable `bar` that isn't inherited from `List` it would be considered non-existing); etc.etc.

So we decided that a mirror should _always_ report the truth about its reflectee, so we won't have things like a `_GrowableList` as the reflectee of a `List` mirror.

This basically means that your problem is caused by the lack of support for private features in reflectable, and that's not something that we can easily fix.

As for workarounds, you might be able to avoid private classes via some simple conventions: With core classes like `List`, you could make the choice to work on them directly as soon as you know that this is the kind of type you're working on:
```dart
void main() {
    final DartLang language = new DartLang("Dart1",new Version(1,23),"Your Dart app is running.");

    final InstanceMirror instanceMirror = rtest.reflect(language);

    // With certain "well-known" types including `List`, drop to non-reflective code when possible.
    final List list = instanceMirror.invokeGetter("names");
    
    // Works - clear!
    print((instanceMirror.invokeGetter("names") as List).last);

    print(list.last); // Rather than `rtest.reflect(list).invokeGetter("last")`.
    ...
}
```

There could be ways to generalize reflectable to handle specific situations of this nature (but this is an extension to reflectable and it might be considered as an ugly wart rather than a meaningful feature, so I won't promise that you'll get it ;-).

The idea would be that you could take the responsibility yourself for the mismatch by telling each `Reflectable` (that is "each mirror system") in some kind of configuration step that it should consult a type translation map if the strict match fails. You would then be able to say "when you see a `_GrowableList` you can give it a `List` mirror".

With that, you wouldn't have to drop down to non-reflective code for your lists, and you wouldn't get weird semantics for anything other than the classes where you have explicitly asked for it. ;-)

**Comment by eernstg** [comment] 2018-04-05 08:41
Considering that the core issue here is the lack of support for access to private names, I'll close this as a duplicate of #33.

**Closed by eernstg** 2018-04-05 08:41 UTC
